############### Generalized FC and wilcoxon testing ############################

# Packages
library(tidyverse)
library(coin)
library(docstring)
library(roxygen2)
library(EnhancedVolcano)


gfc <- function(seqtab, meta, read=F, log.n0=1e-05, mult.corr="fdr",
                var, case, ctrl, feat_type="taxa") {
  #' @description This function calculates differentially abundant ASVs 
  #' based on fdr adjusted wilcoxon tests and then calculates generalized 
  #' fold change, as introduced in Wirbel et al. 2019 Nat Med. Script adapted from: 
  #' https://github.com/zellerlab/crc_meta/blob/master/src/marker_analysis.R 
  #' @param seqtab: character. File path of ASV/OTU table or object if read=F 
  #' @param meta: character. File path of metadata or object if read=F
  #' @param read: boolean. Whether to read files or not. Defaults to false
  #' @param log.n0 integer. Pseudocount for log(X + 1) transformation. 
  #' Default 1e-05
  #' @param mult.corr character. Multiple testing correction. Passed to p.adjust. 
  #' Default fdr/BH
  #' @param var character. Column variable to test on 
  #' @param case character. Case group 
  #' @param ctrl character. Control/Reference group 
  #' @param feat_type character taxa for ASV/OTU/species abundances or function for 
  #' gene/predicted gene abundances 
  #' @usage gfc(seqtab, meta, var, case, ctrl)
  #' @return List containing two dataframes: one containing pvalues and one
  #' containing generalized fold change
  if (read == T){
  seqtab <- as.matrix(read.table(seqtab, sep='\t', header=TRUE, 
                                 stringsAsFactors = FALSE, 
                                 check.names = FALSE, quote='', row.names = 1))
  meta <- read_tsv(meta)
  }
  
  if (feat_type == "functional"){
    log.n0 = 1e-08
  }
  # infer name of sample column 
  sampleid_col <- colnames(meta)[1]
  
  stopifnot(all(meta[sampleid_col] %>% pull() 
                %in% colnames(seqtab)))
  
  # create pval matrix with row for each feature
  p.val <- matrix(NA, nrow=nrow(seqtab), ncol=1, 
                  dimnames=list(row.names(seqtab), c("pval")))
  # duplicate pval matrix to store gfc 
  fc <- p.val
  colnames(fc) <- c("FC") 
  
  
  cat("Calculating pvalue and GFC for each feature...\n")
  pb <- txtProgressBar(max=nrow(seqtab), style=3)
  
  # calculate wilcoxon test and effect size for each feature and study
  for (f in row.names(seqtab)) {
    
      x <- unlist(seqtab[f, meta %>% 
                      filter(.data[[var]]==case) 
                  %>% pull(sampleid_col)])

      y <- unlist(seqtab[f, meta %>% 
                      filter(.data[[var]]==ctrl) 
                  %>% pull(sampleid_col)])
      
      # Wilcoxon
      p.val[f, ] <- wilcox.test(x, y, exact=FALSE)$p.value
      
      # FC
      q.p <- quantile(log2(x+log.n0), probs=seq(.1, .9, .05))
      q.n <- quantile(log2(y+log.n0), probs=seq(.1, .9, .05))
      fc[f,] <- sum(q.p - q.n)/length(q.p)
      # progressbar
      setTxtProgressBar(pb, (pb$getVal()+1))
  }
  cat('\n')
  
  # multiple hypothesis correction
  p.adj <- data.frame(apply(p.val, MARGIN=2, FUN=p.adjust, method=mult.corr),
                      check.names = FALSE)
  ### Return datafram containing pval and log2FC
  
  df_res <- data.frame(p.adj,fc)
  colnames(df_res) <- c("p.adj", "log2FC")

  comparison <- sort(c(case, ctrl))
  
  return_list <- list(res = df_res, groups = comparison)
}

plot_volcano <- function(results_df, ...) {
  #' @description This function takes the ouput of the GFC function and generates 
  #' a volcano plot
  #' @param results_df: object list ouput of GFC containing dataframe with adjusted
  #' p-values and log2 fold change and vector of the groups being compared  
  #' @details additional arguments are passed to EnhancedVolcano
  #' @usage plot_volcano(results_df, ...)
  #' @return Volcano plot generated by EnhancedVolcano
  res <- results_df$res
  groups <- results_df$groups
  EnhancedVolcano(res, x="log2FC", y="p.adj", 
                  lab=rownames(res),
                  labSize = 4,
                  pCutoff = 0.05, 
                  FCcutoff = 1.5, 
                  title = paste(groups[1], 
                                "versus", 
                                groups[2], 
                                sep=" "), 
                  subtitle = NULL,...)
}

